<?php
require_once '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

session_start();

// Check if the required POST data is provided
if (isset($_POST['tableHtml'])) {
    // Retrieve posted data and sanitize it
    $tableHtml = $_POST['tableHtml'];
    $totalAmount = $_POST['totalAmount'] ?? '';
    $startDate = $_POST['startDate'] ?? 'N/A';
    $endDate = $_POST['endDate'] ?? 'N/A';

    // Path to the image (adjust the path based on your directory structure)
    $imagePath = '../public/img/treasury-letter_head.png'; // Adjust this path as needed

    // Check if the image file exists
    if (file_exists($imagePath)) {
        // Get the file type and content
        $imageType = pathinfo($imagePath, PATHINFO_EXTENSION);
        $imageData = file_get_contents($imagePath);
        // Encode the image in base64 for embedding in the HTML
        $base64Image = 'data:image/' . $imageType . ';base64,' . base64_encode($imageData);
    } else {
        // Error if the image is not found
        die('Image file not found at: ' . realpath($imagePath));
    }

    // Set up Dompdf options for rendering the PDF
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isRemoteEnabled', true);

    // Initialize Dompdf with the specified options
    $dompdf = new Dompdf($options);

    // Get the current timestamp and username from the session (if available)
    $timestamp = date('Y-m-d H:i:s');
    $username = isset($_SESSION['user_names']) ? $_SESSION['user_names'] : 'Unknown User';

    // Start building the HTML content for the PDF
    $html = '<html><head>';
    $html .= '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">';
    $html .= '</head><body>';
    $html .= '<div class="container">';

    // Insert the header image at the top of the PDF
    $html .= '<div style="text-align: center; margin-bottom: 20px;">';
    $html .= '<img src="' . $base64Image . '" style="width: 100%; max-width: 600px; height: auto;">';
    $html .= '</div>';
    
    // Add the report title and the date period, with title in bold
    $html .= '<h5 style="text-align: center; font-weight: bold;">PERFORMANCE REPORT</h5>';
    $html .= '<p style="text-align: center; font-size: 15px;"><strong>Period:</strong> ' . htmlspecialchars($startDate) . ' to ' . htmlspecialchars($endDate) . '</p>';
    
    // Add the table HTML content (assumes $tableHtml is sanitized before being passed)
    $html .= '<hr />';
    $html .= $tableHtml;
    $html .= '<hr />';
    
    // Display the total amount, generated by the username, and the timestamp
    $html .= '<p style="text-align: right; font-size: 14px;"><strong>Total Amount Collected: Ksh ' . htmlspecialchars(number_format($totalAmount,0)) . '</strong></p>';
    $html .= '<h6 style="text-align: right; font-size: 12px;">Generated by: ' . htmlspecialchars($username) . '</h6>';
    $html .= '<h6 style="text-align: right; font-size: 12px;">Timestamp: ' . htmlspecialchars($timestamp) . '</h6';
    
    $html .= '</div>';
    $html .= '</body></html>';

    // Load the HTML content into Dompdf
    $dompdf->loadHtml($html);

    // Set the paper size and orientation for the PDF
    $dompdf->setPaper('A4', 'portrait');

    // Render the PDF document
    $dompdf->render();

    // Stream the generated PDF to the browser for download
    $dompdf->stream("report.pdf", ["Attachment" => true]);

} else {
    // Show an error message if no HTML content is received via POST
    echo "No report content provided!";
}
